import type { Metadata } from "next";
import { auth, signOut } from "@/auth";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  pathname,
}: Readonly<{
  children: React.ReactNode;
  pathname: string;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body>
          <div className="navbar bg-neutral">
            <div className="flex-1">
              <a className="btn btn-ghost text-xl">Quetionaire</a>
            </div>
            <div className="flex-none">
              {session ? (
                <div className="dropdown dropdown-end">
                  <div tabIndex={0} role="button" className="btn btn-ghost btn-circle avatar">
                    <div className="w-10 rounded-full">
                      <img
                        alt="User Avatar"
                        src={session.user.image}
                      />
                    </div>
                  </div>
                  <ul
                    tabIndex={0}
                    className="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow">
                  
                    <li>
                      <form
                        action={async () => {
                          "use server";
                          await signOut();
                        }}
                      >
                        <button type="submit">Logout</button>
                      </form>
                    </li>
                  </ul>
                </div>
              ) : (
                <a href="/login" className="btn btn-primary">Login</a>
              )}
            </div>
          </div>
        {children}
      </body>
    </html>
  );
}